### ISSUE TITLE
feature: create Landing page 

### ISSUE THREAD

**Issue by sabarixr** [amfoss/home#8]
**Problem**:
The current [Home](https://home.amfoss.in/) page only displays "Hello world!"

**Solution**:
Design and develop a responsive landing page to be seen at "/"

**Comment by sabarixr** [comment]
Can i get a design?

**Comment by Wreck-X** [comment]
there is no design for this, but your free to create one on figma and get it reviewed for approval. @sabarixr

**Comment by Wreck-X** [comment]
let me know if you still want to do it, ill assign this to you if that's the case

**Comment by hrideshmg** [comment]
@addynair I believe you expressed interest in creating a design for this? Could we get a confirmation for the same, for tracking assignments.
